"""add tenants table and tenant_id to users, courses, meeting_providers

Revision ID: 1e43d685a6a5
Revises: e5f6a7b8c9d0
Create Date: 2026-07-26 10:52:19.185259
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1e43d685a6a5"
down_revision: Union[str, None] = "e5f6a7b8c9d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("logo_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("max_active_students", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_id"), "tenants", ["id"], unique=False)
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.drop_constraint("uq_holiday_date", "academic_holidays", type_="unique")
    op.drop_index("ix_academic_holidays_date", table_name="academic_holidays")
    op.create_index(
        op.f("ix_academic_holidays_date"), "academic_holidays", ["date"], unique=True
    )
    op.drop_constraint("uq_certificate_code", "certificates", type_="unique")
    op.drop_constraint("uq_certificate_enrollment", "certificates", type_="unique")
    op.drop_index("ix_certificates_code", table_name="certificates")
    op.create_index(op.f("ix_certificates_code"), "certificates", ["code"], unique=True)
    op.drop_index("ix_certificates_enrollment_id", table_name="certificates")
    op.create_index(
        op.f("ix_certificates_enrollment_id"),
        "certificates",
        ["enrollment_id"],
        unique=True,
    )
    op.add_column("courses", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_courses_tenant_id"), "courses", ["tenant_id"], unique=False
    )
    op.create_foreign_key(
        None, "courses", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("uq_enrollments_enrollment_code", "enrollments", type_="unique")
    op.drop_index("ix_enrollments_enrollment_code", table_name="enrollments")
    op.create_index(
        op.f("ix_enrollments_enrollment_code"),
        "enrollments",
        ["enrollment_code"],
        unique=True,
    )
    op.drop_index(
        "uq_grade_course", table_name="grades", postgresql_where="(session_id IS NULL)"
    )
    op.drop_index(
        "uq_grade_session",
        table_name="grades",
        postgresql_where="(session_id IS NOT NULL)",
    )
    op.drop_constraint("invoices_code_key", "invoices", type_="unique")
    op.drop_index("ix_invoices_code", table_name="invoices")
    op.create_index(op.f("ix_invoices_code"), "invoices", ["code"], unique=True)
    op.add_column(
        "meeting_providers", sa.Column("tenant_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "meeting_providers_name_key", "meeting_providers", type_="unique"
    )
    op.create_index(
        op.f("ix_meeting_providers_tenant_id"),
        "meeting_providers",
        ["tenant_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_meeting_providers_tenant_name", "meeting_providers", ["tenant_id", "name"]
    )
    op.create_foreign_key(
        None, "meeting_providers", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("users", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.drop_index("ix_users_email", table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_unique_constraint(
        "uq_users_tenant_email", "users", ["tenant_id", "email"]
    )
    op.create_foreign_key(
        None, "users", "tenants", ["tenant_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint("uq_users_tenant_email", "users", type_="unique")
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.drop_column("users", "tenant_id")
    op.drop_constraint(None, "meeting_providers", type_="foreignkey")
    op.drop_constraint(
        "uq_meeting_providers_tenant_name", "meeting_providers", type_="unique"
    )
    op.drop_index(
        op.f("ix_meeting_providers_tenant_id"), table_name="meeting_providers"
    )
    op.create_unique_constraint(
        "meeting_providers_name_key", "meeting_providers", ["name"]
    )
    op.drop_column("meeting_providers", "tenant_id")
    op.drop_index(op.f("ix_invoices_code"), table_name="invoices")
    op.create_index("ix_invoices_code", "invoices", ["code"], unique=False)
    op.create_unique_constraint("invoices_code_key", "invoices", ["code"])
    op.create_index(
        "uq_grade_session",
        "grades",
        ["enrollment_id", "session_id", "evaluation_name"],
        unique=True,
        postgresql_where="(session_id IS NOT NULL)",
    )
    op.create_index(
        "uq_grade_course",
        "grades",
        ["enrollment_id", "evaluation_name"],
        unique=True,
        postgresql_where="(session_id IS NULL)",
    )
    op.drop_index(op.f("ix_enrollments_enrollment_code"), table_name="enrollments")
    op.create_index(
        "ix_enrollments_enrollment_code",
        "enrollments",
        ["enrollment_code"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_enrollments_enrollment_code", "enrollments", ["enrollment_code"]
    )
    op.drop_constraint(None, "courses", type_="foreignkey")
    op.drop_index(op.f("ix_courses_tenant_id"), table_name="courses")
    op.drop_column("courses", "tenant_id")
    op.drop_index(op.f("ix_certificates_enrollment_id"), table_name="certificates")
    op.create_index(
        "ix_certificates_enrollment_id", "certificates", ["enrollment_id"], unique=False
    )
    op.drop_index(op.f("ix_certificates_code"), table_name="certificates")
    op.create_index("ix_certificates_code", "certificates", ["code"], unique=False)
    op.create_unique_constraint(
        "uq_certificate_enrollment", "certificates", ["enrollment_id"]
    )
    op.create_unique_constraint("uq_certificate_code", "certificates", ["code"])
    op.drop_index(op.f("ix_academic_holidays_date"), table_name="academic_holidays")
    op.create_index(
        "ix_academic_holidays_date", "academic_holidays", ["date"], unique=False
    )
    op.create_unique_constraint("uq_holiday_date", "academic_holidays", ["date"])
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_id"), table_name="tenants")
    op.drop_table("tenants")
    # ### end Alembic commands ###
