"""restore the partial unique indexes on grades

`e3f4a5b6c7d8` created `uq_grade_session` and `uq_grade_course` — one score per
evaluation per session, and one per evaluation at course level. The much later
autogenerated tenants migration (`1e43d685a6a5`) dropped both and never put them
back: autogenerate does not model partial indexes, so it read them as drift and
"tidied them away".

The effect only shows on a database built from scratch, which is why it went
unnoticed on incrementally-migrated developer machines. There, `grades` ends up
with no unique index at all, and the gradebook's upsert
(`ON CONFLICT ... DO UPDATE`, see `app/routers/grades.py`) fails outright with
"there is no unique or exclusion constraint matching the ON CONFLICT
specification" — so regrading is broken on every fresh deployment.

Recreated exactly as `e3f4a5b6c7d8` defined them. `IF NOT EXISTS` keeps this a
no-op on databases that predate the drop and still have them.

Revision ID: 5a1b2c3d4e5f
Revises: 4d928cc21a5c
Create Date: 2026-07-28 22:45:00.000000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5a1b2c3d4e5f"
down_revision: Union[str, None] = "4d928cc21a5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX IF NOT EXISTS uq_grade_session ON grades "
            "(enrollment_id, session_id, evaluation_name) "
            "WHERE session_id IS NOT NULL"
        )
    )
    op.execute(
        sa.text(
            "CREATE UNIQUE INDEX IF NOT EXISTS uq_grade_course ON grades "
            "(enrollment_id, evaluation_name) WHERE session_id IS NULL"
        )
    )


def downgrade() -> None:
    op.execute(sa.text("DROP INDEX IF EXISTS uq_grade_course"))
    op.execute(sa.text("DROP INDEX IF EXISTS uq_grade_session"))
