"""add course periodicity and tenant branding columns

The model classes grew new columns that never got a migration:

- `Course.periodicity` (`app/models/course.py`) — creating a course crashed
  with `UndefinedColumn: column "periodicity" of relation "courses" does not
  exist` on every database that had already been migrated.
- The `Tenant` branding/locale fields (`timezone`, `currency`, `primary_color`,
  `secondary_color`, `custom_domain`, `tax_id`, `phone`, `address`) — the
  autogenerated tenants migration (`1e43d685a6a5`) predates them, so creating a
  tenant crashed the same way and every `test_tenant_isolation` test failed.

`timezone` and `currency` get a `server_default` so existing rows keep valid
values under their NOT NULL constraint.

Revision ID: d4e5f6a7b8c9
Revises: b2c3d4e5f6a7
Create Date: 2026-08-01 00:00:00.000000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d4e5f6a7b8c9"
down_revision: Union[str, None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "courses",
        sa.Column("periodicity", sa.String(length=30), nullable=True),
    )

    op.add_column(
        "tenants",
        sa.Column(
            "timezone",
            sa.String(length=50),
            nullable=False,
            server_default="America/Guatemala",
        ),
    )
    op.add_column(
        "tenants",
        sa.Column("currency", sa.String(length=10), nullable=False, server_default="USD"),
    )
    op.add_column(
        "tenants", sa.Column("primary_color", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "tenants", sa.Column("secondary_color", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "tenants", sa.Column("custom_domain", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_tenants_custom_domain"), "tenants", ["custom_domain"], unique=True
    )
    op.add_column("tenants", sa.Column("tax_id", sa.String(length=50), nullable=True))
    op.add_column("tenants", sa.Column("phone", sa.String(length=50), nullable=True))
    op.add_column("tenants", sa.Column("address", sa.String(length=255), nullable=True))


def downgrade() -> None:
    op.drop_index(op.f("ix_tenants_custom_domain"), table_name="tenants")
    for name in (
        "address",
        "phone",
        "tax_id",
        "custom_domain",
        "secondary_color",
        "primary_color",
        "currency",
        "timezone",
    ):
        op.drop_column("tenants", name)
    op.drop_column("courses", "periodicity")
